- Kinvey-Xamarin/Kinvey-Xamarin.csproj
- Kinvey-Xamarin/packages.config
Initial step in integrating PubNub into the Kinvey PCL for Realtime support.
Add NuGet packages for PubNub PCL into Kinvey-Xamarin project.
n/a
> MLIBZ-1623 Add PubNub PCL package to Kinvey-Xamarin PCL

- Kinvey-Xamarin/Store/ReadRequest.cs
Check for null query provider when building mongo query.
Adds a couple of null checks before dereferencing in the `ReadRequest.BuildMongoQuery` method.
All existing tests pass.
> Added safety checks on mongo query building

- Kinvey-Xamarin/Store/PushRequest.cs
Changes push batch size.
Batch size changed from 3 to 10.
Existing tests pass.
Performance tests to measure improved performance.
> Changing batch size of push to 10 based on performance tests

- Kinvey-Xamarin-Android/Push/Push.cs
- Kinvey-Xamarin/Push/AbstractPush.cs
Registers a token for push even if it was previously registered for the same user.
`Push.Initialize` refactored to allow registration on an existing token.
> Push registration changes

- Kinvey-Xamarin/Store/FindRequest.cs
- Kinvey-Xamarin/Store/ReadRequest.cs
Remove default saving of network data in cache
> Prevent creation of cache on network store

- Kinvey.Core/Auth/User.cs
- Kinvey.Core/Utils/KinveyConstants.cs
- TestFramework/Tests.Integration/Tests/UserIntegrationTests.cs
Changed mic ID delimiter from `:` to `.` to match backend change.
> Updated mic id delimiter to period

- Kinvey.Core/Auth/CredentialManager.cs
- Kinvey.Core/Auth/SQLiteCredentialStore.cs
- Kinvey.Core/Core/AbstractKinveyClientRequest.cs
> MLIBZ-2127 Properly persist the clientId in the credential store through soft logout and refresh token usage.

- .cirrus.yml
- .gitignore
- .travis.yml
- TestFramework/Tests.Integration/Tests.Integration.csproj
- TestFramework/Tests.Integration/Tests/ClientIntegrationTests.cs
- TestFramework/Tests.Integration/Tests/DataStoreNetworkIntegrationTests.cs
- TestFramework/Tests.Integration/packages.config
Cirrus CI integration
- `.cirrus.yml`
- Same unit tests
> MLIBZ-2685: Cirrus CI integration

- Kinvey.Core/Auth/User.cs
- Kinvey.Core/Core/AbstractKinveyClientRequest.cs
- Kinvey.Tests/UserUnitTests.cs
Implementation OAuth resource owner password grant authorization against KAS.
Inner changes in the "LoginWithMIC" method.
Change of base URL in the "AbstractKinveyClientRequest.cs".
No changes in tests.
> MLIBZ-2524: Implement OAuth resource owner password grant against KAS, deprecate headless flow. (.NET/Xamarin)

- .cirrus.yml
- Kinvey.Core/Auth/ICredentialStore.cs
- Kinvey.Core/Auth/InMemoryCredentialStore.cs
- Kinvey.Core/Auth/NativeCredentialStore.cs
- Kinvey.Core/Auth/SQLiteCredentialStore.cs
- Kinvey.Core/Client/AbstractClient.cs
- Kinvey.Core/Client/Client.cs
- Kinvey.Core/Offline/ICacheManager.cs
- Kinvey.Core/Offline/SQLiteCacheManager.cs
- Kinvey.Tests/BaseTestClass.cs
Trying to avoid SQLite issues related to multi-thread access
- Locking resources to make sure SQLite access for the same file are thread safe
- Same unit tests
> trying to avoid SQLite issues

- Kinvey-Xamarin-Android/Auth/UserExtension.cs
- Kinvey-Xamarin-iOS/Auth/UserExtension.cs
- testiosapp2/AppDelegate.cs
Typo in the name of the OnOAuthCallbackRecieved handler
Renaming the "OnOAuthCallbackRecieved" to the "OnOAuthCallbackReceived"
No tests
> MLIBZ-2500: [.NET/Xamarin SDK] Typo in the name of the OnOAuthCallbackRecieved handler

- Kinvey.Core/Auth/User.cs
- Kinvey.Core/Kinvey.Core.csproj
- Kinvey.Core/Realtime/RealtimeReconnectionPolicy.cs
- Kinvey.Core/Realtime/RealtimeReconnectionPolicyExtension.cs
- Kinvey.Core/Realtime/RealtimeRouter.cs
- Kinvey.Shared/Kinvey.Shared.projitems
- Kinvey.TestApp.Shared/Constants.cs
- Kinvey.TestApp.Shared/Pages/AddContract.xaml.cs
- Kinvey.TestApp.Shared/Pages/ContractsPage.xaml
- Kinvey.TestApp.Shared/Pages/ContractsPage.xaml.cs
- Kinvey.TestLocalLibApp/Kinvey.TestLocalLibApp/Kinvey.TestLocalLibApp.csproj
- Kinvey.TestNugetPackageLibApp/Kinvey.TestNugetPackageLibApp/Kinvey.TestNugetPackageLibApp.csproj
- Kinvey.Tests/RealtimeIntegrationTests.cs
Kinvey Live Services stop receiving messages after losing and being back internet connection.
The "RealtimeReconnectionPolicy" parameter was added to the "RegisterRealtimeAsync" method of the "User" class. The parameter has default value "RealtimeReconnectionPolicy.None". 
It makes possible to configure PubNub reconnection policy from the client side.
TestRealtimeRegistrationWithRealtimeReconnectionPolicyNone,TestRealtimeRegistrationWithRealtimeReconnectionPolicyLinear, TestRealtimeRegistrationWithRealtimeReconnectionPolicyExponential were added.
> MLIBZ-2727: Kinvey Live Services stop receiving messages.

- Kinvey.Android/Kinvey.Android.csproj
- Kinvey.iOS/Kinvey.iOS.csproj
- Kinvey/Kinvey.csproj
- Makefile
Script to generate API Reference docs
- No changes
- Same tests
> API Reference docs script

- Kinvey.Core/Auth/User.cs
- Kinvey.TestApp.Shared/Constants.cs
Social login methods should be removed in favor of using MIC. 
Marking social network methods as obsolete.
No tests.
> MLIBZ-2857:Deprecate_social_login_methods

- Kinvey.Core/Core/KinveyHeaders.cs
- Kinvey.NuGet/Kinvey.NuGet.nuproj
- Kinvey.TestApp.Shared/Constants.cs
Changing versions.
No changes
No changes
> Preparation of release 3.3.2

- Kinvey-Xamarin-iOS/Push/Push.cs
The "Initialize" and "DisablePush" methods are synchronous, but they spawn off threads in the background. In keeping with the rest of the SDK, it's better to have them run as awaitable methods instead.
Adding the the "InitializeAsync()" and the "DisablePushAsync()" methods to the "Push" class for IOS platform.
No tests
> MLIBZ-1762: Async register and unregister APIs for Push (.NET, Xamarin)(IOS)

- .travis.yml
There are the following issues sometimes
https://travis-ci.org/Kinvey/dotnet-sdk/jobs/523083191
https://travis-ci.org/Kinvey/dotnet-sdk/jobs/523030612
No changes
No tests
> Changing Travis CI settings

- Kinvey.Android/Push/KinveyFCMService.cs
Kinvey .NET SDK should receive pushes from Kinvey console and firebase console
"OnHandleIntent()" method in "KinveyFCMService" class.
No tests
> Support of operating with Kinvey console and firebase console.

- Kinvey.Core/Core/KinveyHeaders.cs
- Kinvey.NuGet/Kinvey.NuGet.nuproj
Release 4.0.0
No changes
No tests
> Preparation of release 4.0.0

- Kinvey.Core/Core/KinveyHeaders.cs
- Kinvey.NuGet/Kinvey.NuGet.nuproj
Preparation of release 4.0.1
No changes
No tests
> Preparation of release 4.0.1

- Kinvey.Core/Core/KinveyHeaders.cs
- Kinvey.NuGet/Kinvey.NuGet.nuproj
Preparation of release 4.1.0
Preparation of release 4.1.0
Preparation of release 4.1.0
> Preparation of release 4.1.0

- Kinvey.Core/Core/KinveyHeaders.cs
- Kinvey.NuGet/Kinvey.NuGet.nuproj
- Kinvey.TestApp.Shared/Constants.cs
> Release 4.2.0 preparation

- Kinvey.Core/Core/KinveyHeaders.cs
- Kinvey.NuGet/Kinvey.NuGet.nuproj
> Preparation of 4.2.1 release

- README.md
The goal of this ticket is to update the README of the repo now that the project setup has been cleaned up.
No changes
No tests
> MLIBZ-3063: Clean up repo README

- Kinvey.Tests/DataStoreTests/DataStoreAutoIntegrationTests.cs
- Kinvey.Tests/DataStoreTests/DataStoreNetworkIntegrationTests.cs
- Kinvey.Tests/DataStoreTests/DataStoreSyncIntegrationTests.cs
Changes according to the review in  
https://github.com/Kinvey/dotnet-sdk/pull/237
No changes
Changes in the current tests.
> MLIBZ-3083: Tech debt for multi insert tests

- Kinvey.Core/Core/KinveyHeaders.cs
- Kinvey.NuGet/Kinvey.NuGet.nuproj
> Preparation of release 4.2.2 

- Kinvey.Core/Core/KinveyHeaders.cs
- Kinvey.NuGet/Kinvey.NuGet.nuproj
> Preparation of release 4.3.0

- Kinvey.Core/Store/SaveRequest.cs
- Kinvey.Tests/DataStoreTests/DataStoreAutoIntegrationTests.cs
Updating Acl and Kmd fields from backend for save operation in Auto data store type.
Logic inside the "SaveRequest" class for Auto data store type.
TestSaveUpdateVersion5ConnectionAvailableAsync()
> MLIBZ-3069: Updating Acl and Kmd fields from backend for save operation

- Kinvey.Android/Kinvey.Android.csproj
- Kinvey.Android/packages.config
- Kinvey.TestApp.Shared/Constants.cs
- Kinvey.iOS/Kinvey.iOS.csproj
- Kinvey.iOS/packages.config
- Kinvey/Kinvey.csproj
- testdroidapp/testdroidapp.csproj
- testdroidapp2/testdroidapp2.csproj
Implement FxCop for linting
No changes
No changes
> MLIBZ-3125: Implement FxCop for linting

- Kinvey.Core/Core/KinveyHeaders.cs
- Kinvey.TestApp.Shared/Constants.cs
> Release 4.3.1

- Kinvey.Core/Store/FindAggregateRequest.cs
- Kinvey.Core/Store/FindRequest.cs
- Kinvey.Core/Store/GetCountRequest.cs
- Kinvey.Core/Store/MultiInsertRequest.cs
- Kinvey.Core/Store/ReadRequest.cs
- Kinvey.Core/Store/RemoveRequest.cs
- Kinvey.Core/Store/SaveRequest.cs
- Kinvey.TestApp.Shared/Pages/AddContract.xaml.cs
- Kinvey.TestApp.Shared/Pages/ContractsPage.xaml.cs
- Kinvey.Tests/DataStoreTests/DataStoreAutoIntegrationTests.cs
The actual behavior:
if some internet or network connection issue occurs in Android or IOS devices, a user will have an exception.
Expected behavior:
if some internet or network connection issue occurs in Android or IOS devices, a user will not have an exception. He will operate with the local data.
Internal implementation in all operations of Auto data store.
No tests
> MLIBZ-3128: Handling the network connection exception in Auto data store type

- Kinvey.Tests/BaseTestClass.cs
- Kinvey.Tests/DataStoreTests/DataStoreAutoIntegrationTests.cs
- Kinvey.Tests/DataStoreTests/DataStoreNetworkIntegrationTests.cs
- Kinvey.Tests/DataStoreTests/DataStoreSyncIntegrationTests.cs
- Kinvey.Tests/Support Files/Code/ConflictErrorEntity.cs
- Kinvey.Tests/Support Files/Code/ForbiddenErrorEntity.cs
- Kinvey.Tests/Support Files/Code/NotFoundErrorEntity.cs
- Kinvey.Tests/Support Files/Code/TestSetup.cs
Add mocks of 400, 401, 403, 404, 409, 500 error responses  for data store 'Grouping/Aggregate' operations (.NET)
Add mocks of 403,404, 409 error responses  for all data store operations.
No changes
TestGetCount400ErrorResponseAsync()
TestGetCount401ErrorResponseAsync()
TestGetCount403ErrorResponseAsync()
TestGetCount404ErrorResponseAsync()
TestGetCount409ErrorResponseAsync()
TestGetCount500ErrorResponseAsync()
TestNetworkStoreGetAverage400ErrorResponseAsync()
TestNetworkStoreGetAverage401ErrorResponseAsync()
TestNetworkStoreGetAverage403ErrorResponseAsync()
TestNetworkStoreGetAverage404ErrorResponseAsync()
TestNetworkStoreGetAverage409ErrorResponseAsync()
TestNetworkStoreGetAverage500ErrorResponseAsync()
TestDelete403ErrorResponseAsync()
TestDelete409ErrorResponseAsync() …
> MLIBZ-2993: Add mocks for data store 'Grouping/Aggregate' operations (.NET)

- Kinvey.NuGet/Kinvey.NuGet.nuproj
- Kinvey.Shared/Core/KinveyHeaders.cs
> Release 4.3.2

- Kinvey.Android/Kinvey.Android.csproj
- Kinvey.Android/packages.config
- Kinvey.TestApp.Shared/Constants.cs
- Kinvey.iOS/Kinvey.iOS.csproj
- Kinvey.iOS/packages.config
- Kinvey/Kinvey.csproj
Removing DocFX from build process in Kinvey.sln projects and running it in Make file.
No changes
No tests
> MLIBZ-3135: Removing DocFX from build process in Kinvey.sln projects and running it in Make file.

- Kinvey.NuGet/Kinvey.NuGet.nuproj
- Kinvey.Shared/Core/KinveyHeaders.cs
> Release 4.3.3

- Kinvey.Shared/Auth/KinveyMICDelegate.cs
- Kinvey.Shared/Core/AbstractKinveyClientRequest.cs
- Kinvey.Shared/Core/IKinveyRequestInitializer.cs
- Kinvey.Shared/Core/KinveyAuthenticator.cs
- Kinvey.Shared/Core/KinveyClientRequestInitializer.cs
- Kinvey.Shared/Core/KinveyDelegate.cs
- Kinvey.Shared/Core/KinveyHeaders.cs
- Kinvey.Shared/Core/NetworkFactory.cs
- Kinvey.Shared/Core/NetworkRequest.cs
- Kinvey.Shared/Core/PreserveAttribute.cs
- Kinvey.Shared/Core/Request.cs
> MLIBZ-3157: Cleanup: Kinvey.Shared/Core project (Into master)

- Kinvey.Shared/Core/AbstractDataRequest.cs
- Kinvey.Shared/Core/AbstractKinveyClientRequest.cs
Removal of dead code by deprecating.
No changes
No tests
> MLIBZ-3157: Cleanup: Kinvey.Shared/Core project (Into next-v5)

- .cirrus.yml
- .travis.yml
- Kinvey.Shared/Store/DataStore.cs
- Kinvey.Shared/Store/DataStoreResponse.cs
- Kinvey.Shared/Store/DataStoreType.cs
- Kinvey.Shared/Store/EnumReduceFunction.cs
- Kinvey.Shared/Store/FindAggregateRequest.cs
- Kinvey.Shared/Store/FindRequest.cs
- Kinvey.Shared/Store/GetCountRequest.cs
- Kinvey.Shared/Store/KinveyDataStoreDelegate.cs
- Kinvey.Shared/Store/MultiInsertRequest.cs
- Kinvey.Shared/Store/PagedPullRequest.cs
- Kinvey.Shared/Store/PullDataStoreResponse.cs
- Kinvey.Shared/Store/PullRequest.cs
- Kinvey.Shared/Store/PushDataStoreResponse.cs
- Kinvey.Shared/Store/PushRequest.cs
- Kinvey.Shared/Store/ReadPolicy.cs
- Kinvey.Shared/Store/ReadRequest.cs
- Kinvey.Shared/Store/RemoveRequest.cs
- Kinvey.Shared/Store/SaveRequest.cs
- Kinvey.Shared/Store/SubscribeRequest.cs
- Kinvey.Shared/Store/SyncDataStoreResponse.cs
- Kinvey.Shared/Store/WritePolicy.cs
- Kinvey.Shared/Store/WriteRequest.cs
- Kinvey.Tests/Kinvey.Tests.csproj
> MLIBZ-3164:  Cleanup: Kinvey.Shared/Store project(Into master)

- Kinvey.NuGet/Kinvey.NuGet.nuproj
- Kinvey.Shared/Core/KinveyHeaders.cs
> Release 4.3.4

- Kinvey.Shared/Model/AccessControlList.cs
- Kinvey.Shared/Model/DeltaSetFetchInfo.cs
- Kinvey.Shared/Model/DeltaSetResponse.cs
- Kinvey.Shared/Model/Entity.cs
- Kinvey.Shared/Model/Error.cs
- Kinvey.Shared/Model/GroupAggregationResults.cs
- Kinvey.Shared/Model/IPersistable.cs
- Kinvey.Shared/Model/KMDEmailVerification.cs
- Kinvey.Shared/Model/KMDPasswordReset.cs
- Kinvey.Shared/Model/KMDStatus.cs
- Kinvey.Shared/Model/KinveyAuthMetaData.cs
- Kinvey.Shared/Model/KinveyAuthSocialID.cs
- Kinvey.Shared/Model/KinveyDeleteResponse.cs
- Kinvey.Shared/Model/KinveyFile.cs
- Kinvey.Shared/Model/KinveyMetaData.cs
- Kinvey.Shared/Model/KinveyMultiInsertResponse.cs
- Kinvey.Shared/Model/KinveyReference.cs
- Kinvey.Shared/Model/KinveyUserMetaData.cs
- Kinvey.Shared/Model/PingResponse.cs
- Kinvey.Shared/Model/ServerError.cs
- Kinvey.Shared/Model/ThirdPartyIdentity.cs
- Kinvey.TestApp.Shared/Constants.cs
> MLIBZ-3160: Cleanup: Kinvey.Shared/Model project (Into Master)

- Kinvey.Shared/Model/AccessControlList.cs
- Kinvey.Shared/Model/DeltaSetFetchInfo.cs
- Kinvey.Shared/Model/DeltaSetResponse.cs
- Kinvey.Shared/Model/Entity.cs
- Kinvey.Shared/Model/Error.cs
- Kinvey.Shared/Model/GroupAggregationResults.cs
- Kinvey.Shared/Model/IPersistable.cs
- Kinvey.Shared/Model/KMDEmailVerification.cs
- Kinvey.Shared/Model/KMDPasswordReset.cs
- Kinvey.Shared/Model/KMDStatus.cs
- Kinvey.Shared/Model/KinveyAuthMetaData.cs
- Kinvey.Shared/Model/KinveyAuthSocialID.cs
- Kinvey.Shared/Model/KinveyDeleteResponse.cs
- Kinvey.Shared/Model/KinveyFile.cs
- Kinvey.Shared/Model/KinveyMetaData.cs
- Kinvey.Shared/Model/KinveyMultiInsertResponse.cs
- Kinvey.Shared/Model/KinveyReference.cs
- Kinvey.Shared/Model/KinveyUserMetaData.cs
- Kinvey.Shared/Model/PingResponse.cs
- Kinvey.Shared/Model/ServerError.cs
- Kinvey.Shared/Model/ThirdPartyIdentity.cs
- Kinvey.TestApp.Shared/Constants.cs
Deprecating of not being used the "KinveyReference<T>" class.
No changes
No tests
> MLIBZ-3160: Cleanup: Kinvey.Shared/Model project (Into next-v5)

- Kinvey.Shared/Utils/HelperMethods.cs
- Kinvey.Shared/Utils/KinveyConstants.cs
- Kinvey.Shared/Utils/Logger.cs
- Kinvey.Shared/Utils/RequirementsValidator.cs
- Kinvey.TestApp.Shared/Constants.cs
> MLIBZ-3166: Cleanup: Kinvey.Shared/Utils project

- Kinvey.Shared/Troubleshooting/EnumErrorCategory.cs
- Kinvey.Shared/Troubleshooting/EnumErrorCode.cs
- Kinvey.Shared/Troubleshooting/KinveyException.cs
- Kinvey.Shared/Troubleshooting/KinveyJsonError.cs
> MLIBZ-3165: Cleanup: Kinvey.Shared/Troubleshooting project(Into master) 

- Kinvey.Shared/Troubleshooting/EnumErrorCategory.cs
- Kinvey.Shared/Troubleshooting/EnumErrorCode.cs
- Kinvey.Shared/Troubleshooting/KinveyException.cs
- Kinvey.Shared/Troubleshooting/KinveyJsonError.cs
- Kinvey.TestApp.Shared/Constants.cs
Deprecating of not being used the "EnumErrorCode" enum values:
ERROR_REALTIME_CRITICAL_VERIFY_CIPHER_KEY
ERROR_REALTIME_CRITICAL_INCORRECT_SUBSBRIBE_KEY
ERROR_REALTIME_CRITICAL_INTERNAL_SERVER_ERROR
ERROR_REALTIME_CRITICAL_BAD_GATEWAY
ERROR_REALTIME_CRITICAL_GATEWAY_TIMEOUT
ERROR_REALTIME_CRITICAL_UNKNOWN
ERROR_REALTIME_WARNING_VERIFY_HOSTNAME
ERROR_REALTIME_WARNING_CHECK_NETWORK_CONNECTION
ERROR_REALTIME_WARNING_NO_NETWORK_CONNECTION
ERROR_REALTIME_WARNING_VERIFY_CIPHER_KEY
ERROR_REALTIME_WARNING_PROTOCOL_ERROR
ERROR_REALTIME_WARNING_SERVER_PROTOCOL_VIOLATION
ERROR_REALTIME_WARNING_MESSAGE_TOO_LARGE
ERROR_REALTIME_WARNING_BAD_REQUEST
ERROR_REALTIME_WARNING_INVALID_PUBLISH_KEY
ERROR_REALTIME_WARNING_PAM_NOT_ENABLED
ERROR_REALTIME_WARNING_INCORRECT_PUBLIC_OR_SECRET_KEY …
> MLIBZ-3165: Cleanup: Kinvey.Shared/Troubleshooting project(Into next-v5)

- Kinvey.Shared/Query/IQueryBuilder.cs
- Kinvey.Shared/Query/KinveyMongoQueryBuilder.cs
- Kinvey.Shared/Query/KinveyQueryExecutor.cs
- Kinvey.Shared/Query/KinveyQueryProvider.cs
- Kinvey.Shared/Query/KinveyQueryVisitor.cs
- Kinvey.Shared/Query/KinveyQueryable.cs
- Kinvey.Shared/Query/StringQueryBuilder.cs
- Kinvey.Shared/Query/VisitorClause.cs
> MLIBZ-3162: Cleanup: Kinvey.Shared/Query project

- Kinvey.Shared/CustomEndpoint/CustomEndpoint.cs
- Kinvey.Shared/CustomEndpoint/CustomEndpointRequest.cs
- Kinvey.Shared/Extensions/CustomExtension.cs
- Kinvey.Shared/Push/AbstractPush.cs
> MLIBZ-3158: Cleanup: Kinvey.Shared/CustomEndpoint,Extension, Push project

- Kinvey.Shared/Offline/CollectionTableMap.cs
- Kinvey.Shared/Offline/ICache.cs
- Kinvey.Shared/Offline/ICacheManager.cs
- Kinvey.Shared/Offline/ISyncQueue.cs
- Kinvey.Shared/Offline/PendingWriteAction.cs
- Kinvey.Shared/Offline/QueryCacheItem.cs
- Kinvey.Shared/Offline/SQLTemplates.cs
- Kinvey.Shared/Offline/SQLiteCache.cs
- Kinvey.Shared/Offline/SQLiteCacheManager.cs
- Kinvey.Shared/Offline/SQLiteSyncQueue.cs
> MLIBZ-3161: Cleanup: Kinvey.Shared/Offline project (To Master)

- Kinvey.Shared/Realtime/KinveyRealtimeDelegate.cs
- Kinvey.Shared/Realtime/KinveyRealtimeStatus.cs
- Kinvey.Shared/Realtime/RealtimeMessage.cs
- Kinvey.Shared/Realtime/RealtimeReconnectionPolicy.cs
- Kinvey.Shared/Realtime/RealtimeReconnectionPolicyExtension.cs
- Kinvey.Shared/Realtime/RealtimeRouter.cs
> MLIBZ-3163: Cleanup: Kinvey.Shared/Realtime project (To Master) 

- Kinvey.Shared/Realtime/RealtimeMessage.cs
Deprecating the "RealtimeMessage<T>" class.
No changes
No tests
> MLIBZ-3163: Cleanup: Kinvey.Shared/Realtime project (To next-v5) 

- Kinvey.Android/Client/AndroidClientBuilder.cs
- Kinvey.Shared/Client/AbstractClient.cs
- Kinvey.Shared/Client/AbstractKinveyClient.cs
- Kinvey.Shared/Client/Client.cs
- Kinvey/Client/DotnetClientBuilder.cs
> MLIBZ-3156: Cleanup: Kinvey.Shared/Client project

- Kinvey.Tests/BaseTestClass.cs
- Kinvey.Tests/ClientTests/ClientIntegrationTests.cs
- Kinvey.Tests/Kinvey.Tests.csproj
- Kinvey.Tests/PushTests/PushTests.cs
- Kinvey.Tests/Support Files/Code/TestSetup.cs
- Kinvey.Tests/UserTests/UserIntegrationTests.cs
Some integration tests fail.
No changes
TestCustomEndpoint()
TestEnablePushViaRestAndroidAsync()
TestEnablePushViaRestIosAsync()
TestDisablePushViaRestAndroidAsync()
TestDisablePushViaRestIosAsync()
TestEnablePushAndroidAsync()
TestEnablePushIosAsync()
TestDisablePushAndroidAsync()
TestDisablePushIosAsync()
TestLoginFacebookAsync()
TestLoginGoogleAsync()
TestLoginTwitterAsync()
TestLoginLinkedInAsync()
TestLoginSalesforceAsync()
TestLoginWithMicResourceOwnerGrantFlowAsync()
TestLoginWithMicResourceOwnerGrantFlowWithServiceIdAsync()
TestLoginMICWithAccessTokenUnauthorizedResponseRefreshTokenExistsAsync()
TestLoginMICWithAccessTokenUnauthorizedResponseTwoAttemptsRetrievingRefreshTokenAsync()
TestLoginMICWithAccessTokenUnauthorizedResponseCredentialsAreEmptyAsync() …
> Fixing integration tests.

- Kinvey.NuGet/Kinvey.NuGet.nuproj
- Kinvey.Shared/Core/KinveyHeaders.cs
> feat: .NET release 4.3.5

- Kinvey.Android/Push/FCMPush.cs
- Kinvey.Shared/Auth/KinveyAuthRequest.cs
- Kinvey.Shared/Auth/LoginRequest.cs
- Kinvey.Shared/Auth/User.cs
- Kinvey.Shared/Client/Client.cs
- Kinvey.Shared/Core/AbstractKinveyClientRequest.cs
- Kinvey.Shared/CustomEndpoint/CustomEndpoint.cs
- Kinvey.Shared/File/File.cs
- Kinvey.Shared/File/KinveyFileRequest.cs
- Kinvey.Shared/Offline/SQLiteCacheManager.cs
- Kinvey.Shared/Push/AbstractPush.cs
- Kinvey.Shared/Realtime/RealtimeRouter.cs
- Kinvey.Shared/Store/DataStore.cs
- Kinvey.Shared/Store/FindAggregateRequest.cs
- Kinvey.Shared/Store/FindRequest.cs
- Kinvey.Shared/Store/GetCountRequest.cs
- Kinvey.Shared/Store/MultiInsertRequest.cs
- Kinvey.Shared/Store/PagedPullRequest.cs
- Kinvey.Shared/Store/PullRequest.cs
- Kinvey.Shared/Store/PushRequest.cs
- Kinvey.Shared/Store/ReadRequest.cs
- Kinvey.Shared/Store/RemoveRequest.cs
- Kinvey.Shared/Store/SaveRequest.cs
- Kinvey.Shared/Store/SubscribeRequest.cs
- Kinvey.iOS/Push/Push.cs
See comments in the
https://kinvey.atlassian.net/browse/MLIBZ-3170
ALL SDK methods are having await/async operations.
No tests
> MLIBZ-3170: calling ConfigureAwait(false) on the awaited tasks Kinvey.

- Kinvey.NuGet/Kinvey.NuGet.nuproj
- Kinvey.Shared/Core/KinveyHeaders.cs
> Release 4.3.6

- .cirrus.yml
- .gitignore
- .gitmodules
- Kinvey.NuGet/Kinvey.NuGet.nuproj
- Kinvey.Shared/Auth/KinveyAuthRequest.cs
- Kinvey.Shared/Core/AbstractKinveyClientRequest.cs
- Kinvey.Shared/Core/KinveyHeaders.cs
- Kinvey.Shared/File/KinveyFileRequest.cs
- Kinvey.Shared/Model/KinveyUserMetaData.cs
- Kinvey.Shared/Troubleshooting/KinveyException.cs
- Kinvey.Shared/Troubleshooting/KinveyJsonError.cs
- Kinvey.TestApp.Shared/Pages/ContractsPage.xaml
- Kinvey.TestApp.Shared/Pages/ContractsPage.xaml.cs
- Kinvey.Tests/BaseTestClass.cs
- Kinvey.Tests/UserTests/UserIntegrationTests.cs
- sqlite-net/LICENSE.md
- sqlite-net/SQLite.sln
- sqlite-net/nuget/SQLite-net-base/SQLite-net-base.csproj
- sqlite-net/nuget/SQLite-net-sqlcipher/SQLite-net-sqlcipher.csproj
- sqlite-net/nuget/SQLite-net-std/SQLite-net-std.csproj
- sqlite-net/nuget/SQLite-net/SQLite-net.csproj
- sqlite-net/nuget/SQLite-net/packages.config
- sqlite-net/src/AssemblyInfo.cs
- sqlite-net/src/SQLite.cs
- sqlite-net/src/SQLiteAsync.cs
Changes:
* Added LastLoginTime property serving the new llt value returned in the meta data
* Version up from 4.3.6 to 4.4.0
* Remove submodule and add sqlite-net directly to the project
* Remove choco usage in Windows build of Cirrus CI
* Update macOS build of Cirrus CI to use Catalina image
> KDEV-687: Add LastLoginTime to KinveyUserMetaData

- Kinvey.Shared/Model/Error.cs
- Kinvey.Shared/Store/MultiInsertRequest.cs
- Kinvey.Shared/Store/PushRequest.cs
Updated the error model for multi insert operations.
> KDEV-804: Fix missing error info for batch save operations
