Kinvey/dotnet-sdk

Kinvey-Xamarin/AbstractPush.cs
Fixes the problem with unregistering push device tokens.
- Add the device token parameter to the unregister request. 
- Remove the constructor for `PushPayload` that takes a single parameter, since it should never be used.
- Tested locally to confirm that the push payload in the request is correct.
- Tested the backend against REST API to confirm that the correct payload results in unregistering the token.
=> Mlibz 1709 unregister push

Kinvey-Xamarin/Push/AbstractPush.cs
Fixes the problem with unregistering push device tokens. (This PR corresponds to https://github.com/Kinvey/dotnet-sdk/pull/97 on v1)
- Add the device token parameter to the unregister request. 
- Remove the constructor for `PushPayload` that takes a single parameter, since it should never be used.
- Tested locally to confirm that the push payload in the request is correct.
- Tested the backend against REST API to confirm that the correct payload results in unregistering the token.
=> Fixed push unregister bug on v3

Kinvey-Xamarin/Store/ReadRequest.cs
This PR adds safety checks to delta set fetch. In MLIBZ-1409, a crash was reported during delta fetch. While I was unable to reproduce the cache, the stack trace suggests a missing `lmt` from a third party data source could have caused it.
If `lmt` is missing, delta set caching will be ignored and the fetch will default to a network fetch.
All existing tests pass.
=> Prevent exception during delta set fetch, when `lmt` is missing

Kinvey-Xamarin/Model/KinveyDeleteResponse.cs, Kinvey-Xamarin/Offline/ICache.cs, Kinvey-Xamarin/Offline/ISyncQueue.cs, Kinvey-Xamarin/Offline/SQLiteCache.cs, Kinvey-Xamarin/Offline/SQLiteSyncQueue.cs, Kinvey-Xamarin/Store/DataStore.cs, Kinvey-Xamarin/Store/ReadRequest.cs, TestFramework/Tests.Integration/Tests/DataStoreSyncIntegrationTests.cs
New `DataStore` APIs - `ClearCache()` and `Purge()`
- Minor changes to the `ICache` and `ISyncQueue` interfaces (backwards compatible)
- New tests to cover the new APIs
Added new tests to cover the new APIs
=> Added apis to clear cache and purge the sync queue

Kinvey-Xamarin-Android.nuspec, Kinvey-Xamarin-Android/Kinvey-Xamarin-Android.csproj, Kinvey-Xamarin-Android/MainApplication.cs, Kinvey-Xamarin-Android/packages.config, Kinvey-Xamarin-iOS.nuspec, Kinvey-Xamarin-iOS/Kinvey-Xamarin-iOS.csproj, Kinvey-Xamarin-iOS/packages.config, Kinvey-Xamarin.nuspec, Kinvey-Xamarin/Core/KinveyHeaders.cs, Kinvey-Xamarin/Kinvey-Xamarin.csproj, Kinvey-Xamarin/packages.config
This PR is for adding device info in request headers.  This is done in the `X-Kinvey-Device-Info` header.  This information includes OS, OS version, and basic device model.
Example iOS output:  `X-Kinvey-Device-Info -> iOS 10.2 iPhone`
Example Android output: `X-Kinvey-Device-Info -> Android 4.4.2 GT-P5210`
The `Xam.Plugin.DeviceInfo` package was added as a dependency for our PCL as well as our platform packages.  In addition to this, a new header was added to our requests.
No new tests are added here, because the device info package does not support getting information from a Mac OS.  The test that this is working as intended is the fact that all current tests pass as normal, despite not being able to retrieve device info on the Mac.
=> MLIBZ-1539 Initial commit of code and packages to retrieve device info

Kinvey-Xamarin/Store/DataStore.cs, TestFramework/Tests.Integration/Tests/DataStoreNetworkIntegrationTests.cs
Adds a new overloaded `collection` method to `DataStore` with a default `StoreType`.
- New method in `DataStore`.
- Change the default storetype to `CACHE`, which is what we mention on devcenter.
- New tests.
- New test to cover the new API
- Existing tests pass.
=> Reinstate default storetype constructor for datastore

Kinvey-Xamarin-Android/Push/Push.cs
Fix for MLIBZ-1709: push re-registration error.
Fixed error where if a device ID was found, registration with the backend was not attempted.  Now, push registration with the backend is always attempted.
Tested on device.
=> Mlibz 1709 register push

Kinvey-Xamarin/Auth/SQLiteCredentialStore.cs, Kinvey-Xamarin/Auth/User.cs, Kinvey-Xamarin/Core/AbstractKinveyClientRequest.cs
Fix logic around re-auth with refresh token.  Fix persistence of access token in SQLite.  Fix parsing of location in MIC flow to be more robust.
Changes made to the retry logic of requests failing with `401`, as well as to persistence of `access_token` in SQLite offline store.
Manual testing.
=> MLIBZ-1775 Fix logic around re-auth with refresh token.

Kinvey-Xamarin/Auth/User.cs, TestFramework/Tests.Unit/Tests.Unit.csproj, TestFramework/Tests.Unit/Tests/UserUnitTests.cs
Fixes for both [MLIBZ-1783](https://kinvey.atlassian.net/browse/MLIBZ-1783) and [MLIBZ-1774](https://kinvey.atlassian.net/browse/MLIBZ-1774).  Addresses a bug with MIC automated authorization flow where any exceptions thrown during this process were not properly propagated up to the user.  The exceptions were being trapped by the SDK, which is incorrect behavior.
Correctly throw any `KinveyException` caught during MIC automated auth flow.
Create new `KinveyException` for any unexpected general exception.
Add unit test to check behavior against mock 504 response.
=> MLIBZ-1783 Correctly throw exceptions in MIC automated auth flow

Kinvey.Core/Auth/Credential.cs, Kinvey.Core/Auth/InMemoryCredentialStore.cs, Kinvey.Core/Auth/SQLCredential.cs, Kinvey.Core/Auth/SQLiteCredentialStore.cs, Kinvey.Core/Auth/User.cs, Kinvey.Core/Auth/UserRequestFactory.cs, Kinvey.Core/Model/KinveyAuthMetaData.cs
There is an issue with updating the user object where `_socialIdentity` information is missing.
Made the `_socialIdentity` object part of the `User` and `Credential` classes, to ensure persistence through app runs and user object updates.
Manual testing.
=> MLIBZ-1846 Add socialIdentity object to both the User and Credential classes.

Kinvey.Core/Auth/User.cs, TestFramework/Tests.Integration/Tests/UserIntegrationTests.cs
The `ResetPasswordAsync` method on the `User` class is an instance method, when it should be static.
Change method to be static on the `User` class, which is consistent with the other SDKs.
Added integration test.
=> MLIBZ-1816 Make the ResetPassword method static

Kinvey.Core.nuspec, Kinvey.Core/Kinvey.Core.csproj
Issues with upgrading to the latest version of the SDK for some customers, because the PubNub package is more restrictive in its support of PCL profiles.
Change the PubNub package used to `PubNubNetPlatform 3.8.7`, in order to support more PCL profiles.
Manually tested upgrades with a couple of sample apps.
=> Change PubNub version to PubNubNetPlatform 3.8.7, in order to support more PCL profiles.

Kinvey.Core/Offline/SQLiteCache.cs, TestFramework/Tests.Integration/Tests/DataStoreSyncIntegrationTests.cs
It is permitted for an entity created on the client in a `SYNC` store to provide their own ID.  In this case, the operation is now identified as a `PUT` rather than a `POST`, but the item does not yet exist in the database.  In this case, it should not be assumed that the database entry exists, and we should insert if it does not.
Change the `Update` on the database to `InsertOrReplace`.
Unit test added.
=> MLIBZ-1850 Change database update to upsert for case where ID is provided in a entity created in SYNC store.

Kinvey.Core/Offline/SQLiteCacheManager.cs, TestFramework/Tests.Integration/Tests/UserIntegrationTests.cs
Issues with clearing state during logout of app. Results in an exception being thrown when logging back in and accessing the offline DB.
Clear state in the `SQLiteCacheManager` which holds mappings to cached tables.
Manual tests, since this manifests itself in an app lifecycle.
=> MLIBZ-1916 Clean up SQLiteCacheManager state during logout

Kinvey.Core/Offline/SQLiteCache.cs, TestFramework/TestSupportFiles/ToDo.cs, TestFramework/Tests.Integration/Tests/DataStoreSyncIntegrationTests.cs
Sorting did not appear to work for sync store items in the offline DB.
The sorting issue was only for `DateTime` objects, which were not previously supported.  They are now supported for sorting in the offline case.
Integration tests added.
=> MLIBZ-1912 Support sort of DateTime objects in offline store.

Kinvey.Core/Model/KinveyAuthMetaData.cs, Kinvey.Core/Model/KinveyAuthSocialID.cs
Custom fields can be added to the `_socialIdentity` object, but the SDK does not have a way to access them.
Add `Attributes` dictionary to both the `_socialIdentity` and `kinveyAuth` objects.
Manual testing via MIC.
=> MLIBZ-1964 Add attribute dictionary to _socialIdentity and kinveyAuth objects to capture custom fields.

Kinvey.Core/Query/KinveyQueryVisitor.cs, TestFramework/Tests.Integration/Tests/DataStoreNetworkIntegrationTests.cs
In LINQ, there are a couple of different ways to represent equals queries (`Equals`, `==`).  There was a bug in handling multiple `where` queries when using `==`.
Ensure we check for multiple where clauses and add commas in the mongo-syntax query string when appropriate.
Unit tests added to check against the different ways to express equals comparisons.
=> MLIBZ-1943 Add support for different forms of multiple where clause equals comparisons.

Kinvey.Core/Store/DataStore.cs, TestFramework/Tests.Integration/Tests/DataStoreCacheIntegrationTests.cs, TestFramework/Tests.Integration/Tests/DataStoreNetworkIntegrationTests.cs, TestFramework/Tests.Integration/Tests/DataStoreSyncIntegrationTests.cs
Currently, for consistency, the SDK returns a `List<T>` for `FindByID()`.  It should return just `T`.
Changed the method signature to return only `T`, rather than a list.
Tests added for all `DataStore` types.
=> MLIBZ-1896 Change method signature of FindByID to return an entity

Kinvey.Core/Offline/ISyncQueue.cs, Kinvey.Core/Offline/SQLiteSyncQueue.cs, Kinvey.Core/Store/DataStore.cs, Kinvey.Core/Store/PushRequest.cs, TestFramework/Tests.Unit/Tests.Unit.csproj, TestFramework/Tests.Unit/Tests/DataStoreUnitTests.cs
Make sure the code is thread safe, so in case of any operation is performed while `sync()` still running everything still consistent
* Deleting the pending operation by `key` (pending operation key) instead of `entityId`
* To be added soon
=> MLIBZ-1743: sync queue race condition

Kinvey.Core/Auth/Credential.cs, Kinvey.Core/Auth/InMemoryCredentialStore.cs, Kinvey.Core/Auth/SQLCredential.cs, Kinvey.Core/Auth/SQLiteCredentialStore.cs, Kinvey.Core/Auth/User.cs, Kinvey.Core/Auth/UserRequestFactory.cs, Kinvey.Core/Core/AbstractKinveyClientRequest.cs, TestFramework/Tests.Integration/Tests/UserIntegrationTests.cs
As part of MLIBZ-1803, this PR adds support for a custom MIC ID to be passed into MIC login methods.
The previous method names have been deprecated, in favor of `LoginWithMIC()`.  And `micID` has been added as an optional parameter, defaulting to `appKey`, as was the case before.
Tests added for normal MIC flow
=> MLIBZ-1836 Add clientID to MIC methods

Kinvey.Core.nuspec
Nuget package dependencies are applied to all installations, rather than being based on platform/framework.
Change the dependencies section of the `.nuspec` file to support grouping based on target framework.
Manual testing, since this has to do with package installation in an app.
=> Update nuspec file to have group dependencies

Kinvey.Core/Core/NetworkFactory.cs, Kinvey.Core/Kinvey.Core.csproj, Kinvey.Core/Offline/SQLiteCache.cs, Kinvey.Core/Store/DataStore.cs, Kinvey.Core/Store/PagedPullRequest.cs
New feature - add automatic paging to `dataStore.pull()`. This allows a large collection to be pulled to the app without the developer having to write pagination logic using `skip` and `limit`.
This PR also adds pipelining to the page-by-page pull.  A multithreaded producer dumps pages into a queue from which a single consumer writes them to cache.
- New request to implement auto-paging (`PagedPullRequest`)
- New setting in DataStore (`AutoPagination`, defaults to `false`)
TBD
=> Automatic pagination on DataStore.pull()

Kinvey.Core/Offline/SQLiteSyncQueue.cs, Kinvey.Core/Utils/KinveyConstants.cs, TestFramework/Tests.Integration/Tests/DataStoreSyncIntegrationTests.cs
In the cases where offline data is stored, if an entity is created on the client with a custom ID, all save actions performed on that client ID appear as `PUT` operation. In this case, if another modification was made to the entity and saved, this would also appear as a `PUT`, and duplicated in the sync queue.
Add check for enqueuing a `PUT` operation for an entity when another `PUT` already exists for that entity.  In this case, we do not enqueue anything.
Unit tests added to cover custom ID case.
=> MLIBZ-2027 Add check for enqueuing a PUT when a PUT already exists for that entityId.

Kinvey.Core/Offline/SQLiteCacheManager.cs
Show Sqlite commands for debug purposes
* Adding a `TraceListener` in the Sqlite connection so we can log the commands
* No need
=> Show Sqlite commands for debug purposes

Kinvey.Core/Realtime/Stream.cs, TestFramework/Tests.Integration/Tests/RealtimeIntegrationTests.cs
Provide a way to access the ACL of a stream, since a REST endpoint exists to get the ACL.
A method has been added to the `Stream` object to get the ACL of the stream. The return value is the same type of object (`StreamAccessControlList`) as the one used to grant ACL permissions.
Test assertion added.
=> MLIBZ-2098 Add support for getting the ACL settings on a stream.

Kinvey.Core/Auth/User.cs
In normal MIC flow, the refresh token is not being respected, and users are being logged out after the TTL expires.
The root cause is that the MIC Client ID is not being properly persisted in the credential store, which is preventing the refresh token from being used properly.
Tested with customer app.
=> MLIBZ-2196 Correctly persist client ID in credential store for normal MIC flow.

Kinvey.Core/Client/Client.cs, Kinvey.Core/Utils/KinveyConstants.cs, TestFramework/Tests.Unit/Tests/ClientUnitTests.cs
Feature to create a new way of setting an instance ID on a client initialization, so that correct API and Auth hostnames are created without having to provide a FQDN.
New setter created in the client builder to set the instance ID.
Unit tests
=> MLIBZ-2334 Add separated SetInstanceID method to client builder.

Kinvey.Core/Realtime/RealtimeRouter.cs, Kinvey.Core/Utils/KinveyConstants.cs, TestFramework/Tests.Integration/Tests/RealtimeIntegrationTests.cs
A case was not being handled for collection subscription, where the ACL for an entity may not be set for being globally readable, but the active user may be allowed to read the update. In this case, the Live Service update was properly coming through to the SDK, but the SDK was filtering out this message because it did not correspond to a valid channel.
When a collection subscription channel is added, also add a collection-active user specific channel, in order to capture updates with the aforementioned ACL.
Integrated tests.
=> MLIBZ-2223 Live service collection updates filtered out

Kinvey.Core/Auth/User.cs, TestFramework/Tests.Unit/Tests/UserUnitTests.cs
With MIC v3, **_"scope=openid"_** has to be passed in as a parameter to the **_/oauth/auth_** endpoint. This was missing in the render URL in normal MIC flow.
Add **_"scope=openid"_** to the render URL passed back to the MIC delegate during normal MIC flow.
Unit test added to make sure **_"scope=openid"_** is present in the URL.
=> MLIBZ-2499 Add scope=openid to render URL for MIC. Add unit test.

Kinvey.Core/Store/ReadRequest.cs, Kinvey.Core/Utils/KinveyConstants.cs
The `ParameterValueOutOfRange` error was not being correctly handled by the SDK.
When receiving this error, handle by performing a delta set initial GET request, so that the `QueryCache` table entry is made with a new `x-kinvey-request-start` time.
Manual. Unit test will be added as part of `MLIBZ-2471`.
=> MLIBZ-2545 Added check for ParameterValueOutOfRange

Kinvey-Xamarin-Android.nuspec, Kinvey-Xamarin-iOS.nuspec, Kinvey.Core.nuspec, Kinvey.Core/Kinvey.Core.csproj, Kinvey.Core/packages.config
An update of the Microsoft Visual Studio IDE made a change to the NuGet package manager that cause our SDK to fail to install.
Make changes to the appropriate `.nuspec` files to allow the SDK to be installed again.
This is an installation issue, so manual testing was done on both Mac and Windows.
=> MLIBZ-2578 Changes to .nuspec files to fix installation issue.

Kinvey.Core/Auth/User.cs, Kinvey.Core/Troubleshooting/EnumErrorCode.cs, Kinvey.Core/Troubleshooting/KinveyException.cs, Kinvey.Core/Utils/KinveyConstants.cs, TestFramework/Tests.Unit/Tests/UserUnitTests.cs
MIC errors from a redirect URI can now appear in the URI itself, rather than the expected `code`. The goal of this PR is to detect if an error is passed this way, and if so, parse it and throw the appropriate `Exception`.
Look for an `error` and `error_description` passed in the redirect URI, and throw an `Exception` with this information.
Unit test added.
=> MLIBZ-2529 Parse error string from redirect URI

Kinvey.Core/File/File.cs, TestFramework/Tests.Integration/Tests/FileIntegrationTests.cs
Customer reported that the name of the `downloadAsync()` method name should actually start with a capital letter, to meet .NET convention.
Deprecated the `downloadAsync()` method in favor of `DownloadAsync()`.
Modified existing tests.
=> MLIBZ-1417 Deprecate old method name format

Kinvey-Xamarin-Android/Auth/AndroidNativeCredentialStore.cs, Kinvey-Xamarin-iOS/Auth/IOSNativeCredentialStore.cs, Kinvey.Core/Auth/NativeCredentialStore.cs
Missing Disposable implementations
- iOS and Android Native Credential Stores were missing the Disposable implementation
- Same unit tests
=> Missing Disposable implementations

Kinvey.Core/Auth/User.cs, Kinvey.Tests/UserUnitTests.cs, TestFramework/Tests.Integration/Tests/UserIntegrationTests.cs
Deprecate the "loginWithMIC()" method with the "redirectURI" parameter for automated authorization grant flow
The method
"static public async Task LoginWithMIC(string username, string password, string redirectURI, string micID = null, AbstractClient userClient = null, CancellationToken ct = default(CancellationToken))"
got deprecated.
Some changes in the following tests:
TestMIC_LoginWithMIC_HeadlessFlow, TestMIC_LoginWithMIC_HeadlessFlow_ClientID, TestLoginWithMIC
=> MLIBZ-2761:Deprecate `loginWithMIC()` method for automated authorization grant flow

.travis.yml, Kinvey.Core/Core/NetworkFactory.cs, Kinvey.TestApp.Shared/Constants.cs, Kinvey.Tests/BaseTestClass.cs, Kinvey.Tests/DataStoreCacheIntegrationTests.cs, Kinvey.Tests/DataStoreNetworkIntegrationTests.cs
There is not any URL query encoding in Kinvey HTTP requests. As a result the sign "+" is being lost, when a request reaches a server side.
Changes in the "NetworkFactory" class. Adding URL encoding for query in HTTP requests.
TestDeltaSetWithQueryPullReturnCorrectNumberOfUpdates()
TestDeleteByQueryStringValueWithPlusSymbolEqualExpressionAsync()
TestGetCountAsyncWithQuery()
TestNetworkStoreFindByMongoQueryWithPlusSymbol()
=> MLIBZ-2666: "+" sign is removed from query.

Kinvey.Core/Auth/User.cs, Kinvey.Core/Core/AbstractKinveyClientRequest.cs, Kinvey.Core/Extensions/CustomExtension.cs, Kinvey.Core/Kinvey.Core.csproj, Kinvey.Shared/Kinvey.Shared.projitems, Kinvey.TestApp.Shared/Constants.cs, Kinvey.Tests/BaseTestClass.cs, Kinvey.Tests/Support Files/TestSetup.cs, Kinvey.Tests/UserIntegrationTests.cs
The library attempts to store for subsequent usage the "refresh_token" of the MIC token response. In case we have locally stored a refresh token we will try to use it when we receive an error from the server for expired credentials. We need to handle cases when the "refresh_token"  is null or absent.
LoginWithMICInternal(), GetMICAccessTokenAsync() in the "User" class.
ExecuteUnparsedAsync() in the "AbstractKinveyClientRequest" class.
TestLoginMICWithAccessTokenUnauthorizedResponseAsync()
=> MLIBZ-2826: Correctly handle missing or null refresh token.

Kinvey.Core/Store/DataStore.cs, Kinvey.Core/Store/DataStoreType.cs, Kinvey.TestApp.Shared/Constants.cs
Since the CACHE DataStore will no longer be supported, the goal of this ticket is to place a deprecation notice in place for this type. 
Making the field "CACHE" as deprecated in  DataStoreType.cs.
No tests
=> MLIBZ-2852:Deprecate CACHE DataStore type

Kinvey.TestApp.Shared/Constants.cs, Kinvey.Tests/BaseTestClass.cs, Kinvey.Tests/DataStoreAutoIntegrationTests.cs, Kinvey.Tests/Support Files/TestSetup.cs
The QA team has prepared a set of tests for verifying the functionality of the `AUTO` data store. The goal of this ticket is to implement as many of these tickets as is feasible.
No changes
TestFindNetworkConnectionAvailableAsync()
TestFindWithQueryNetworkConnectionAvailableAsync()
TestFindWithSkipLimitQueryNetworkConnectionAvailableAsync()
TestFindWithDeltaSetTurnOnNetworkConnectionAvailableAsync()
TestFindDescendingOrderNetworkConnectionAvailableAsync()
TestFindDeletingItemNetworkConnectionAvailableAsync()
TestFindInvalidQueryNetworkConnectionAvailableAsync()
TestFindInvalidPermissionsNetworkConnectionAvailableAsync()
TestFindNetworkConnectionIssueAsync()
TestFindNetworkConnectionEliminatedAsync()
TestFindWithQueryNetworkConnectionIssueAsync() …
=> MLIBZ-2885: Implement `AUTO` DataStore tests

.travis.yml, Kinvey.Core/Offline/SQLiteSyncQueue.cs, Kinvey.Core/Store/RemoveRequest.cs, Kinvey.Core/Store/SaveRequest.cs, Kinvey.Tests/DataStoreAutoIntegrationTests.cs, Kinvey.Tests/Support Files/TestSetup.cs
The QA team has prepared a set of tests for verifying the functionality of the AUTO data store. The goal of this ticket is to implement as many of these tickets as is feasible.
SaveAsync(), RemoveAsync(string entityID), RemoveAsync(IQueryable<object> query) API methods.
**Sync**
TestSyncDataConnectionAvailableAsync()
TestSyncDataWithQueryConnectionAvailableAsync()
TestSyncDataNetworkConnectionIssueAsync()
**PendingSyncCount**
TestGetSyncCountConnectionAvailableAsync()
**ClearSync**
TestPurgeAllItemsConnectionAvailableAsync()
TestPurgeCreatedItemsAccordingToQueryConnectionAvailableAsync()
TestPurgeUpdatedItemsAccordingToQueryConnectionAvailableAsync()
**Clear**
TestClearAllItemsConnectionAvailableAsync()
TestClearItemsByQueryConnectionAvailableAsync() …
=> MLIBZ-2890: Complete implementation of AUTO DataStore tests

Kinvey.Tests/BaseTestClass.cs, Kinvey.Tests/Support Files/TestSetup.cs, Kinvey.Tests/UserIntegrationTests.cs
For the scope of this ticket, concentrate on mocking a 401 - Unauthorized server response, and validate through unit tests that we correctly handle this error. This includes:
No refresh token: log out the active user and delete the active user credential from the credential store.
Refresh token present: try to use the refresh token
No changes
TestLoginMICWithAccessTokenUnauthorizedResponseTwoAttemptsRetrievingRefreshTokenAsync()
TestLoginMICWithAccessTokenUnauthorizedResponseCredentialsAreEmptyAsync()
TestLoginMICWithAccessTokenUnauthorizedResponseRefreshTokenIsNullAsync()
TestLoginMICWithAccessTokenUnauthorizedResponseRefreshTokenIsEmptyAsync()
TestLoginMICWithAccessTokenUnauthorizedResponseRefreshTokenIsNullStringAsync()
=> MLIBZ-2842: Create mock responses to simulate user and login server errors (5xx)

Kinvey.Core/Auth/User.cs, Kinvey.Tests/UserTests/UserIntegrationTests.cs, TestFramework/Tests.Integration/Tests/UserIntegrationTests.cs
According to the Pariveda team functionality like this is typically a property instead of a method. Instead of .IsActive() this would be .Active
The "IsActive()" method in the "User" class.
TestLoginUserPassAsync()
TestSharedClientLoginAsync()
TestLoginAsync()
=> MLIBZ-1415: IsActive should be a property and not a method

.travis.yml, Kinvey.Android/Push/FcmPush.cs, Kinvey.Core/Troubleshooting/EnumErrorCode.cs, Kinvey.Core/Troubleshooting/KinveyException.cs, Kinvey.TestApp.Shared/Constants.cs
When you don't configure push completely push registration fails silently: http://devcenter.kinvey.com/xamarin/guides/push#RegisteringtheDevice
Kinvey SDK should provide a warning to the developer to inform them that push may not be configured correctly.
The "InitializeAsync()" method of the  "FCMPush"  class.
No tests
=> MLIBZ-1881:Push registration fails silently when configuration is not correct (Manifest changes)

Kinvey.Android/Push/FcmPush.cs
To unregister the device from FCM altogether, delete the instance ID by calling the DeleteInstanceId method on the FirebaseInstanceId class. 
https://docs.microsoft.com/en-us/xamarin/android/data-cloud/google-messaging/remote-notifications-with-fcm?tabs=windows#disconnecting-from-fcm
The "DisablePushAsync" in the "FCMPush" class.
No tests.
=> Adding  FirebaseInstanceId.Instance.DeleteInstanceId() to DisablePushAsync

Kinvey.Android/Push/FcmPush.cs, Kinvey.Core/Troubleshooting/EnumErrorCode.cs, Kinvey.Core/Troubleshooting/KinveyException.cs
When you don't configure push completely push registration fails silently: http://devcenter.kinvey.com/xamarin/guides/push#RegisteringtheDevice
Kinvey SDK should provide a warning to the developer to inform them that push may not be configured correctly.
The "InitializeAsync()" method of the "FCMPush" class.
No tests
=> MLIBZ-2989: Push registration fails silently when configuration is not correct (Class overrides)

Kinvey.Core/Auth/KinveyAuthRequest.cs, Kinvey.Core/Client/AbstractKinveyClient.cs, Kinvey.Core/Client/Client.cs, Kinvey.Core/Core/AbstractKinveyClientRequest.cs, Kinvey.Core/Core/KinveyHeaders.cs, Kinvey.Core/Utils/KinveyConstants.cs, Kinvey.TestApp.Shared/Constants.cs, Kinvey.Tests/BaseTestClass.cs, Kinvey.Tests/ClientTests/ClientIntegrationTests.cs
Customers should have possibility to change Kinvey api version.
New method in the Builder class:
SetApiVersion()
New property in the Client class:
ApiVersion{get;}
TestSetApiVersionAuthRequests()
TestSetApiVersionKinveyClientRequests()
=> MLIBZ-3027:Creating a method for changing Kinvey api version in the Client.Builder.

Kinvey.Core/Core/NetworkFactory.cs, Kinvey.Core/Kinvey.Core.csproj, Kinvey.Core/Model/Error.cs, Kinvey.Core/Model/KinveyDataStoreResponse.cs, Kinvey.Core/Model/KinveyMultiInsertResponse.cs, Kinvey.Core/Store/DataStore.cs, Kinvey.Core/Store/MultiInsertRequest.cs, Kinvey.Core/Store/SaveRequest.cs, Kinvey.Core/Store/WriteRequest.cs, Kinvey.Core/Troubleshooting/EnumErrorCode.cs, Kinvey.Core/Troubleshooting/KinveyException.cs, Kinvey.Core/Utils/HelperMethods.cs, Kinvey.Core/Utils/KinveyConstants.cs, Kinvey.Shared/Kinvey.Shared.projitems, Kinvey.TestApp.Shared/Constants.cs, Kinvey.Tests/BaseTestClass.cs, Kinvey.Tests/DataStoreTests/DataStoreAutoIntegrationTests.cs, Kinvey.Tests/DataStoreTests/DataStoreNetworkIntegrationTests.cs, Kinvey.Tests/DataStoreTests/DataStoreSyncIntegrationTests.cs, Kinvey.Tests/Support Files/Code/TestSetup.cs
Implementing multi-record insert feature
Adding overloaded version of the "Save()" method in the Data Store.
NETWORK:
TestSaveMultiInsertNewItemsAsync()
TestSaveMultiInsertNewItemsExistingItemsAsync()
TestSaveMultiInsertEmptyArrayAsync()
TestSaveMultiInsertCount101Async()
TestSaveMultiInsertIncorrectKinveyApiVersionAsync()
TestSaveMultiInsertNewItemsExistingItemsWithErrorsAsync()
TestSaveMultiInsertThrowingExceptionAsync()
SYNC:
TestSyncStoreSaveMultiInsertNewItemsAsync()
TestSyncStoreSaveMultiInsertNewItemsExistingItemsAsync()
TestSyncStoreSaveMultiInsertEmptyArrayAsync()
TestSyncStoreSaveMultiInsertCount101Async()
TestSyncStoreSaveMultiInsertIncorrectKinveyApiVersionAsync()
TestSyncStoreSaveMultiInsertNewItemsExistingItemsWithErrorsAsync() …
=> MLIBZ-3015:Implement multi-record insert

Kinvey.Core/Store/MultiInsertRequest.cs, Kinvey.Core/Store/PushRequest.cs, Kinvey.TestApp.Shared/Constants.cs, Kinvey.Tests/BaseTestClass.cs, Kinvey.Tests/DataStoreTests/DataStoreAutoIntegrationTests.cs, Kinvey.Tests/DataStoreTests/DataStoreNetworkIntegrationTests.cs, Kinvey.Tests/DataStoreTests/DataStoreSyncIntegrationTests.cs, Kinvey.Tests/Support Files/Code/ToDo.cs
Implement all the tests defined in the test set spreadsheet that will be linked in the epic when completed.
Bug fixes in multi insert operation.
A bug fix in  pushing local entities for PUT operation.
//Auto store
TestSaveCreateVersion5ConnectionAvailableAsync()
TestSaveCreateVersion5ConnectionIssueAsync()
TestSaveUpdateVersion5ConnectionAvailableAsync()
TestSaveUpdateVersion5ConnectionIssueAsync()
TestSaveMultiInsertNewItemsConnectionAvailableAsync()
TestSaveMultiInsertNewItemsConnectionIssueAsync()
TestSaveMultiInsertExistingItemsConnectionAvailableAsync()
TestSaveMultiInsertNewItemsExistingItemsConnectionAvailableAsync()
TestSaveMultiInsertNewItemsExistingItemsConnectionIssueAsync()
TestSaveInvalidPermissionsAsync() (until bug) …
=> MLIBZ-3020:Implement test set for multi-record insert

Kinvey.TestApp.Shared/Constants.cs, Kinvey.Tests/BaseTestClass.cs, Kinvey.Tests/DataStoreTests/DataStoreNetworkIntegrationTests.cs, Kinvey.Tests/Support Files/Code/TestSetup.cs
Simulating various 4xx/5xx responses that we get from the backend, to ensure that we correctly handle these backend errors. 
No Changes
TestNetworkStoreFindByID400ErrorResponseAsync()
TestNetworkStoreFindByID401ErrorResponseAsync()
TestNetworkStoreFindByID404ErrorResponseAsync()
TestNetworkStoreFindByID500ErrorResponseAsync()
=> MLIBZ-2992: Add mocks for data store 'Find' operations (.NET)

Kinvey.Core/Core/AbstractKinveyClientRequest.cs, Kinvey.Core/Kinvey.Core.csproj, Kinvey.Core/Model/ServerError.cs, Kinvey.Core/Utils/KinveyConstants.cs, Kinvey.Shared/Kinvey.Shared.projitems, Kinvey.TestApp.Shared/Constants.cs, Kinvey.Tests/BaseTestClass.cs, Kinvey.Tests/DataStoreTests/DataStoreAutoIntegrationTests.cs, Kinvey.Tests/DataStoreTests/DataStoreSyncIntegrationTests.cs, Kinvey.Tests/Support Files/Code/TestSetup.cs, Kinvey.Tests/UserTests/UserIntegrationTests.cs
The logic for handling 401 responses should be extended according to all possible cases.
AbstractKinveyClientRequest<T> class.
TestSaveInvalidPermissionsAsync()
TestPushNewItemsInvalidPermissionsAsync()
TestSyncStorePushNewItemsInvalidPermissionsAsync()
TestActionWithCorruptedAuthTokenAsync()
=> MLIBZ-3070: Unauthorized response (401) issue

Kinvey.Core/Store/MultiInsertRequest.cs, Kinvey.Core/Store/RemoveRequest.cs, Kinvey.Core/Store/SaveRequest.cs, Kinvey.Tests/DataStoreTests/DataStoreAutoIntegrationTests.cs
Adding entities to the pending actions for Auto data store type if any Kinvey  or Network connection exception occurs.
Internal implementation in Save and Remove operations of the data store.
TestDeleteByQueryInvalidPermissionsConnectionAvailableAsync()
TestDeleteByQueryInvalidPermissionsNetworkConnectionIssueAsync()
TestDeleteByIdNotFoundConnectionAvailableAsync()
TestDeleteByIdNotFoundConnectionIssueAsync()
TestSaveInvalidPermissionsNetworkConnectionAvailableAsync()
TestSaveDataNetworkConnectionIssueAsync()
TestSaveMultiInsertInvalidPermissionsAsync()
TestSaveMultiInsertNewItemsConnectionIssueAsync()
=> MLIBZ-3111: Auto data store type. Adding entities to the pending actions.

Kinvey.TestLocalLibApp/Kinvey.TestLocalLibApp.Android/Kinvey.TestLocalLibApp.Android.csproj, Kinvey.TestLocalLibApp/Kinvey.TestLocalLibApp.UWP/Kinvey.TestLocalLibApp.UWP.csproj, Kinvey.TestLocalLibApp/Kinvey.TestLocalLibApp.iOS/Kinvey.TestLocalLibApp.iOS.csproj, Kinvey.TestLocalLibApp/Kinvey.TestLocalLibApp/Kinvey.TestLocalLibApp.csproj, Kinvey.Tests/BaseTestClass.cs, Kinvey.Tests/DataStoreTests/DataStoreAutoIntegrationTests.cs, Kinvey.Tests/DataStoreTests/DataStoreNetworkIntegrationTests.cs, Kinvey.Tests/DataStoreTests/DataStoreSyncIntegrationTests.cs, Kinvey.Tests/Support Files/Code/TestSetup.cs, test-ios-app/test-ios-app.csproj, testiosapp2/testiosapp2.csproj
Simulating various 4xx/5xx responses that we get from the backend, to ensure that we correctly handle these backend errors.
No Changes
TestDelete400ErrorResponseAsync()
TestDelete401ErrorResponseAsync()
TestDelete404ErrorResponseAsync()
TestDelete500ErrorResponseAsync()
TestDeleteByQuery401ErrorResponseAsync()
TestSave400ErrorResponseAsync()
TestSave401ErrorResponseAsync()
TestSave500ErrorResponseAsync()
TestSaveMultiInsertExisting400ErrorResponseInUpdateAsync()
TestSaveMultiInsertExisting500ErrorResponseInMultiInsertAsync()
TestSaveMultiInsertExisting500ErrorResponseInUpdateAsync()
TestSaveMultiInsertInvalidPermissionsForUpdateAsync()
TestSaveMultiInsertThrowing400ErrorResponseInMultiInsertAsync()
TestSaveMultiInsertThrowing400ErrorResponseInUpdateAsync() …
=> MLIBZ-2994: Add mocks for data store 'Save/Remove' operations (.NET)

Kinvey.Tests/BaseTestClass.cs, Kinvey.Tests/DataStoreTests/DataStoreAutoIntegrationTests.cs, Kinvey.Tests/Support Files/Code/BadRequestErrorEntity.cs, Kinvey.Tests/Support Files/Code/InternalServerErrorEntity.cs
Simulating various 4xx/5xx responses that we get from the backend, to ensure that we correctly handle these backend errors.
No changes
TestPush400ErrorResponseAsync()
TestPush401ErrorResponseAsync()
TestPush500ErrorResponseAsync()
TestPullDataNetwork400ErrorResponseAsync()
TestPullDataNetwork401ErrorResponseAsync()
TestPullDataNetwork500ErrorResponseAsync()
TestSyncPush400ErrorResponseAsync()
TestSyncPull400ErrorResponseAsync()
TestSyncPush401ErrorResponseAsync()
TestSyncPull401ErrorResponseAsync()
TestSyncPush500ErrorResponseAsync()
TestSyncPull500ErrorResponseAsync()
=> MLIBZ-2995: Add mocks for data store 'Pull/Push/Sync' operations (.NET)

Kinvey.Shared/Store/MultiInsertRequest.cs, Kinvey.TestApp.Shared/Constants.cs, Kinvey.Tests/DataStoreTests/DataStoreAutoIntegrationTests.cs
In a batch of multi-insert requests, if a whole batch fails, the response to the whole operation is an error.
The logic of handling exceptions in the multi-insert operation.
TestSaveMultiInsert201CountWithErrorsAsync()
=> MLIBZ-3145: Failing in a batch of multi-insert requests

Kinvey.Shared/Auth/KinveyAuthRequest.cs, Kinvey.Shared/Core/AbstractKinveyClientRequest.cs, Kinvey.Shared/Troubleshooting/KinveyException.cs, Kinvey.Shared/Utils/HelperMethods.cs, Kinvey.Tests/BaseTestClass.cs, Kinvey.Tests/DataStoreTests/DataStoreNetworkIntegrationTests.cs, Kinvey.Tests/Support Files/Code/FakeRequest.cs, Kinvey.Tests/Support Files/Code/TestSetup.cs, Kinvey.Tests/UserTests/UserIntegrationTests.cs
A request from support to be more detailed in our error messaging around parsing errors in responses from the backend. If we fail to process a response from the backend because we cannot correctly parse the response body, let's return a more descriptive error message, rather than the generic error message currently returned.
An example of a more descriptive error message given by support is:
"Received an array for API call {endpoint}, but expected an object".
Handling JsonException for all network requests.
TestLoginUserPassParsingJsonErrorAsync()
TestNetworkStoreParsingJsonErrorAsync()
TestNetworkStoreParsingJsonErrorSync()
=> MLIBZ-2821: Provide more descriptive message for response body parsing errors

Kinvey.Shared/Store/DataStore.cs, Kinvey.Shared/Store/ReadPolicy.cs, Kinvey.Shared/Store/ReadRequest.cs, Kinvey.Tests/DataStoreTests/DataStoreAutoIntegrationTests.cs, Kinvey.Tests/DataStoreTests/DataStoreCacheIntegrationTests.cs, Kinvey.Tests/DataStoreTests/DataStoreNetworkIntegrationTests.cs, Kinvey.Tests/DataStoreTests/DataStoreSyncIntegrationTests.cs, Kinvey.Tests/UserTests/UserIntegrationTests.cs
Removal of dead and not needed code by deprecating.
DataStore.cs
```
GetCustomRequestProperties()
SetCustomRequestProperties (JObject customheaders)
SetCustomRequestProperty (string key, JObject value)
FindAsync(IQueryable<object> query = null, KinveyDelegate<List<T>> cacheResults = null, CancellationToken ct = default(CancellationToken))
FindByIDAsync(string entityID, KinveyDelegate<T> cacheResult = null, CancellationToken ct = default(CancellationToken))
GetCountAsync(IQueryable<object> query = null, KinveyDelegate<uint> cacheCount = null, CancellationToken ct = default(CancellationToken))
GroupAndAggregateAsync(EnumReduceFunction reduceFunction, string groupField = "", string aggregateField = "", IQueryable<object> query = null, KinveyDelegate<List<GroupAggregationResults>> …
```
=> MLIBZ-3164: Cleanup: Kinvey.Shared/Store project (Into next-v5) 

Kinvey.Shared/Offline/PendingWriteAction.cs, Kinvey.Shared/Offline/SQLTemplates.cs, Kinvey.Shared/Offline/SQLiteCache.cs, Kinvey.Shared/Offline/SQLiteCacheManager.cs
Deprecating of not being used code.
1. The "toNetworkRequest()" method in the "PendingWriteAction" class.
2. The "GetAsync(string query)" method in the "SQLiteCache" class.
3. The "getCollectionTables()" method in the "SQLiteCacheManager" class.
4. The "getCollectionTablesAsync()" method in the "SQLiteCacheManager" class.
5. The "SQLTemplates" class, the "SQLTemplates.TableItem" class, the "SQLTemplates.OfflineEntity" class, the "SQLTemplates.QueueItem" class, the "SQLTemplates.QueryItem" class, the "SQLTemplates.OfflineMetaData" class.
No changes
No tests
=> MLIBZ-3161: Cleanup: Kinvey.Shared/Offline project (To next-v5)

Kinvey.Shared/Auth/KinveyAuthRequest.cs, Kinvey.Shared/Core/AbstractKinveyClientRequest.cs, Kinvey.Shared/File/KinveyFileRequest.cs, Kinvey.Shared/Troubleshooting/KinveyException.cs, Kinvey.Shared/Troubleshooting/KinveyJsonError.cs, Kinvey.TestApp.Shared/Pages/ContractsPage.xaml, Kinvey.TestApp.Shared/Pages/ContractsPage.xaml.cs
Prior dotnet core `3.0` the `EnsureSuccessStatusCode` disposes the content:
https://github.com/dotnet/corefx/blob/release/2.2/src/System.Net.Http/src/System/Net/Http/HttpResponseMessage.cs#L164
The new implementation simply throws:
https://github.com/dotnet/corefx/blob/release/3.0/src/System.Net.Http/src/System/Net/Http/HttpResponseMessage.cs#L172
Since the SDK raises KinveyException after a failed status code check the response is already disposed and the error info cannot be obtained.
Changes:
* Use an extension method which resembles the dotnet core 3+ implementation of `EnsureSuccessStatusCode`.
* Update TestApp for CustomEndpoint tests
=> KDEV-722: Fix missing info in KinveyException

Kinvey.Shared/Store/MultiInsertRequest.cs, Kinvey.Tests/BaseTestClass.cs, Kinvey.Tests/DataStoreTests/DataStoreAutoIntegrationTests.cs, Kinvey.Tests/DataStoreTests/DataStoreNetworkIntegrationTests.cs, Kinvey.Tests/DataStoreTests/DataStoreSyncIntegrationTests.cs
* Always return all errors when making a save of multiple entities. Previously we checked if there were only errors in the response and threw an Exception. Now the request will return a response which contain only errors.
=> KDEV-803: Return all errors when saving multiple entities
